services:
  #nginx
  web:
    image: nginx:stable-alpine
    container_name: web-server
    ports:
      - "8083:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  php:
    build:
      dockerfile: ./php/Dockerfile
    container_name: php8.2
    volumes:
      - ./app:/app

  #mysql
  #redis