services:
  #nginx
  web:
    image: nginx:stable-alpine
    container_name: web-server
    ports:
      - "8083:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  php:
    build:
      dockerfile: ./php/Dockerfile
    container_name: php8.2
    volumes:
      - ./app:/app
  #mysql
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
  #redis

volumes:
  mysqldata: